# Generated by Django 3.2.4 on 2021-07-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='image',
            field=models.ImageField(upload_to='snakes'),
        ),
    ]
